// agents.js

export const agents = [
  { value: "سفر عبادة", label: "سفر عبادة" },
  { value: "فيصل", label: "فيصل" },
  { value: "مبرور", label: "مبرور" },
  { value: "كمال الوفاء", label: "كمال الوفاء" },
  { value: "المؤذن", label: "المؤذن" },
  { value: "جيار اوغلو", label: "جيار اوغلو" },
  { value: "يونايتد", label: "يونايتد" },
  { value: "الراحة", label: "الراحة" },
  { value: "الامام", label: "الامام" },
  { value: "جبل النور", label: "جبل النور" },
  { value: "يورو أيار", label: "يورو أيار" },
  { value: "يونيفيرسال", label: "يونيفيرسال" },
  { value: "عنيقا", label: "عنيقا" },
  { value: "حمزة ترافل", label: "حمزة ترافل" },
  { value: "القدر", label: "القدر" },
  { value: "روضة", label: "روضة" },
  { value: "الجعيدي", label: "الجعيدي" },
  { value: "اسكوي", label: "اسكوي" },
  { value: "نوى", label: "نوى" },
  { value: "لبيك", label: "لبيك" },
  { value: "حياة ترافل", label: "حياة ترافل" },
  { value: "المناسك", label: "المناسك" },
  { value: "الايمان", label: "الايمان" },
  { value: "سبات", label: "سبات" },
  { value: "ابداع الياسر", label: "ابداع الياسر" },
  { value: "القبلتين", label: "القبلتين" },
  { value: "عبدالرحمن", label: "عبدالرحمن" },
  { value: "القصواء", label: "القصواء" },
  { value: "مدينة اير", label: "مدينة اير" },
  { value: "السفير", label: "السفير" },
  { value: "مكة حج", label: "مكة حج" },
  { value: "ايكو", label: "ايكو" },
  { value: "بسمة تور", label: "بسمة تور" },
  { value: "ايفريست", label: "ايفريست" },
  { value: "فالنسيا", label: "فالنسيا" },
  { value: "وسق تورز", label: "وسق تورز" },
  { value: "دي بي اتش", label: "دي بي اتش" },
  { value: "ايراسا", label: "ايراسا" },
  { value: "طاف", label: "طاف" },
  { value: "الزياداب", label: "الزياداب" },
  { value: "المقام", label: "المقام" },
  { value: "سواديش", label: "سواديش" },
  { value: "ايكون", label: "ايكون" },
  { value: "ميقات", label: "ميقات" },
  { value: "جنى جول", label: "جنى جول" },
  { value: "امداد", label: "امداد" },
  { value: "حبيب الله", label: "حبيب الله" },
  { value: "ترتيل", label: "ترتيل" },
  { value: "افرست", label: "افرست" },
  { value: "منى", label: "منى" },
  { value: "مكة اكسبرس", label: "مكة اكسبرس" },
  { value: "سوناتا", label: "سوناتا" },
  { value: "الكوثر", label: "الكوثر" },
  { value: "كامن", label: "كامن" },
  { value: "يلملم", label: "يلملم" },
  { value: "اورانج ترافل", label: "اورانج ترافل" },
  { value: "الفضيلة", label: "الفضيلة" },
  { value: "خاص", label: "خاص..." },
  { value: "خارجي", label: "خارجي" },
  { value: "Other", label: "Other..." },
];
