// nationalities.js

export const nationalities = [
  { value: "Pakistan", label: "باكستان 🇵🇰 Pakistan" },
  { value: "India", label: "الهند 🇮🇳 India" },
  { value: "Bangladesh", label: "بنغلاديش 🇧🇩 Bangladesh" },
  { value: "Turkey", label: "تركيا 🇹🇷 Turkey" },
  { value: "Egypt", label: "مصر 🇪🇬 Egypt" },
  { value: "France", label: "فرنسا 🇫🇷 France" },
  { value: "Germany", label: "ألمانيا 🇩🇪 Germany" },
  { value: "Indonesia", label: "إندونيسيا 🇮🇩 Indonesia" },
  { value: "Iraq", label: "العراق 🇮🇶 Iraq" },
  { value: "Palestine", label: "فلسطين 🇵🇸 Palestine" },
  { value: "Jordan", label: "الأردن 🇯🇴 Jordan" },
  { value: "Lebanon", label: "لبنان 🇱🇧 Lebanon" },
  { value: "Syria", label: "سوريا 🇸🇾 Syria" },
  { value: "Kyrgyzstan", label: "قيرغيزستان 🇰🇬 Kyrgyzstan" },
  { value: "Armenia", label: "أرمينيا 🇦🇲 Armenia" },
  { value: "Azerbaijan", label: "أذربيجان 🇦🇿 Azerbaijan" },
  { value: "Bahrain", label: "البحرين 🇧🇭 Bahrain" },
  { value: "Bhutan", label: "بوتان 🇧🇹 Bhutan" },
  { value: "Brunei", label: "بروناي 🇧🇳 Brunei" },
  { value: "Cambodia", label: "كمبوديا 🇰🇭 Cambodia" },
  { value: "China", label: "الصين 🇨🇳 China" },
  { value: "Cyprus", label: "قبرص 🇨🇾 Cyprus" },
  { value: "Georgia", label: "جورجيا 🇬🇪 Georgia" },
  { value: "Iran", label: "إيران 🇮🇷 Iran" },
  { value: "Israel", label: "إسرائيل 🇮🇱 Israel" },
  { value: "Italy", label: "إيطاليا 🇮🇹 Italy" },
  { value: "Japan", label: "اليابان 🇯🇵 Japan" },
  { value: "Kazakhstan", label: "كازاخستان 🇰🇿 Kazakhstan" },
  { value: "Kenya", label: "كينيا 🇰🇪 Kenya" },
  { value: "Kuwait", label: "الكويت 🇰🇼 Kuwait" },
  { value: "Laos", label: "لاوس 🇱🇦 Laos" },
  { value: "Liberia", label: "ليبيريا 🇱🇷 Liberia" },
  { value: "Libya", label: "ليبيا 🇱🇾 Libya" },
  { value: "Malaysia", label: "ماليزيا 🇲🇾 Malaysia" },
  { value: "Maldives", label: "جزر المالديف 🇲🇻 Maldives" },
  { value: "Mongolia", label: "منغوليا 🇲🇳 Mongolia" },
  { value: "Myanmar", label: "ميانمار 🇲🇲 Myanmar" },
  { value: "Nepal", label: "نيبال 🇳🇵 Nepal" },
  { value: "Nigeria", label: "نيجيريا 🇳🇬 Nigeria" },
  { value: "North Korea", label: "كوريا الشمالية 🇰🇵 North Korea" },
  { value: "Oman", label: "عمان 🇴🇲 Oman" },
  { value: "Philippines", label: "الفلبين 🇵🇭 Philippines" },
  { value: "Qatar", label: "قطر 🇶🇦 Qatar" },
  { value: "Russia", label: "روسيا 🇷🇺 Russia" },
  { value: "Saudi Arabia", label: "السعودية 🇸🇦 Saudi Arabia" },
  { value: "Singapore", label: "سنغافورة 🇸🇬 Singapore" },
  { value: "South Korea", label: "كوريا الجنوبية 🇰🇷 South Korea" },
  { value: "Sri Lanka", label: "سريلانكا 🇱🇰 Sri Lanka" },
  { value: "Taiwan", label: "تايوان 🇹🇼 Taiwan" },
  { value: "Tajikistan", label: "طاجيكستان 🇹🇯 Tajikistan" },
  { value: "Thailand", label: "تايلاند 🇹🇭 Thailand" },
  { value: "Timor-Leste", label: "تيمور الشرقية 🇹🇱 Timor-Leste" },
  { value: "Turkmenistan", label: "تركمانستان 🇹🇲 Turkmenistan" },
  {
    value: "United Arab Emirates",
    label: "الإمارات العربية المتحدة 🇦🇪 United Arab Emirates",
  },
  { value: "USA", label: "الولايات المتحدة الأمريكية 🇺🇸 USA" },
  { value: "Uzbekistan", label: "أوزبكستان 🇺🇿 Uzbekistan" },
  { value: "Vietnam", label: "فيتنام 🇻🇳 Vietnam" },
  { value: "Yemen", label: "اليمن 🇾🇪 Yemen" },
  { value: "Afghanistan", label: "أفغانستان 🇦🇫 Afghanistan" },
  { value: "Other", label: "Other..." },
];
